import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() =>
      ['en', 'es', 'ja', 'fr', 'de', 'it', 'zh_Hans'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? esText = '',
    String? jaText = '',
    String? frText = '',
    String? deText = '',
    String? itText = '',
    String? zh_HansText = '',
  }) =>
      [
        enText,
        esText,
        jaText,
        frText,
        deText,
        itText,
        zh_HansText
      ][languageIndex] ??
      '';
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // HomePage
  {
    'vgo6xkl0': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // Events
  {
    'ybsl0owd': {
      'en': 'Ur mom',
      'de': 'Deine Mutter',
      'es': 'Tu mamá',
      'fr': 'Ta mère',
      'it': 'Tua mamma',
      'ja': 'あなたのお母さん',
      'zh_Hans': '你妈妈',
    },
    'vqrob0gm': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // Notifications
  {
    'ic7yfb2d': {
      'en': 'Notifications',
      'de': 'Benachrichtigungen',
      'es': 'Notificaciones',
      'fr': 'Avis',
      'it': 'Notifiche',
      'ja': '通知',
      'zh_Hans': '通知',
    },
    'ovaggf7w': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // Announcements
  {
    'lznq1wwo': {
      'en': 'Announcements',
      'de': 'Ankündigungen',
      'es': 'Anuncios',
      'fr': 'Annonces',
      'it': 'Annunci',
      'ja': 'お知らせ',
      'zh_Hans': '公告',
    },
    '0qzj91xg': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // Menu
  {
    'si27okfu': {
      'en': 'Schools',
      'de': 'Schulen',
      'es': 'Escuelas',
      'fr': 'Écoles',
      'it': 'Scuole',
      'ja': '学校',
      'zh_Hans': '学校',
    },
    'kos0rq10': {
      'en': 'Report a Bug',
      'de': 'Melde einen technischen Fehler',
      'es': 'Reportar un error',
      'fr': 'Signaler un bug',
      'it': 'Segnalare un bug',
      'ja': 'バグを報告',
      'zh_Hans': '报告错误',
    },
    '8ksfk5gc': {
      'en': 'Settings',
      'de': 'Einstellungen',
      'es': 'Ajustes',
      'fr': 'Réglages',
      'it': 'Impostazioni',
      'ja': '設定',
      'zh_Hans': '设置',
    },
    'ber2r5oj': {
      'en': 'About',
      'de': 'Um',
      'es': 'Sobre',
      'fr': 'À propos de',
      'it': 'Di',
      'ja': '約',
      'zh_Hans': '关于',
    },
    '3cnbthkp': {
      'en': 'Log Out',
      'de': 'Ausloggen',
      'es': 'Cerrar sesión',
      'fr': 'Se déconnecter',
      'it': 'Disconnettersi',
      'ja': 'ログアウト',
      'zh_Hans': '登出',
    },
    'zsnpy2p2': {
      'en': 'RoverLink',
      'de': 'RoverLink',
      'es': 'RoverLink',
      'fr': 'RoverLink',
      'it': 'RoverLink',
      'ja': 'ローバーリンク',
      'zh_Hans': '罗孚林克',
    },
    'jk2shv6o': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // ReportAbsence
  {
    'jwwhxy1w': {
      'en': 'Student\'s Full Name',
      'de': 'Vollständiger Name des Schülers',
      'es': 'Nombre completo del estudiante',
      'fr': 'Nom complet de l\'étudiant',
      'it': 'Nome completo dello studente',
      'ja': '学生の氏名',
      'zh_Hans': '学生全名',
    },
    'hj5u572u': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'u546gkcb': {
      'en': 'Easton Area High School',
      'de': 'Schule',
      'es': 'escuela',
      'fr': 'école',
      'it': 'scuola',
      'ja': '学校',
      'zh_Hans': '学校',
    },
    'td3ko32x': {
      'en': 'Easton Area Middle School',
      'de': 'da größere schule',
      'es': 'escuela da biger',
      'fr': 'une grande école',
      'it': 'da più grande scuola',
      'ja': 'ダ ビガー スクール',
      'zh_Hans': '大学校',
    },
    'ezn4z6q4': {
      'en': 'Palmer Elementary School',
      'de': 'ba smolllll elementar',
      'es': 'ba smolllll elemental',
      'fr': 'ba smolllll élémentaire',
      'it': 'ba smolllll elementare',
      'ja': 'ba smollll エレメンタリー',
      'zh_Hans': '小基础',
    },
    'i5wqd0wb': {
      'en': 'Forks Elementary School',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'lgw1476k': {
      'en': 'Tracy Elementary School',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    '4n4muv23': {
      'en': 'Cheston Elementary School',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    '6y83xwa9': {
      'en': 'Paxinosa Elementary School',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    '8y02wpa2': {
      'en': 'Shawnee Elementary School',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'e8rbnjjm': {
      'en': 'March Elementary School',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    '850a9x9w': {
      'en': 'Easton Cyber Academy',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'k5ogbgzy': {
      'en': 'Please select a School',
      'de': 'Bitte wählen Sie eine Schule aus',
      'es': 'Por favor seleccione una Escuela',
      'fr': 'Veuillez sélectionner une école',
      'it': 'Seleziona una scuola',
      'ja': '学校を選択してください',
      'zh_Hans': '请选择学校',
    },
    'a472bdc8': {
      'en': 'Teacher',
      'de': 'Lehrer',
      'es': 'Maestro',
      'fr': 'Prof',
      'it': 'Insegnante',
      'ja': '先生',
      'zh_Hans': '老师',
    },
    '35ht5wfx': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    '8n71aobg': {
      'en': 'Kindergarten',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'v7qlkwqb': {
      'en': '1st Grade',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'ik2w56qi': {
      'en': '2nd Grade',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'i2rktvs9': {
      'en': '3rd Grade',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    '0lc101up': {
      'en': '4th Grade',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'o2xfsvtw': {
      'en': '5th Grade',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'njw81idy': {
      'en': '6th Grade',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    '6wsb5xj4': {
      'en': '7th Grade',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'k065ravw': {
      'en': '8th Grade',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'qgrf3zve': {
      'en': '9th Grade',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    '5hcgqi8u': {
      'en': '10th Grade',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'bfses5vq': {
      'en': '11th Grade',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'nsb0pryy': {
      'en': '12th Grade',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'tmvvrqyu': {
      'en': 'Please select a grade level',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'a2wcicz4': {
      'en': 'Date',
      'de': 'Datum',
      'es': 'Fecha',
      'fr': 'Date',
      'it': 'Data',
      'ja': '日にち',
      'zh_Hans': '日期',
    },
    'ax4onkre': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'xrqv4ouh': {
      'en': 'Reason for Absence',
      'de': 'Grund der Abwesenheit',
      'es': 'Motivo de la ausencia',
      'fr': 'Motif d\'absence',
      'it': 'Motivo dell\'assenza',
      'ja': '欠席理由',
      'zh_Hans': '缺席原因',
    },
    'rmbtcthh': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    '2cpyhjt3': {
      'en': 'Add Doctor\'s Note Photo',
      'de': 'Arztbrief Foto hinzufügen',
      'es': 'Agregar foto de la nota del médico',
      'fr': 'Ajouter une photo de note du médecin',
      'it': 'Aggiungi la foto della nota del medico',
      'ja': '医師のメモの写真を追加',
      'zh_Hans': '添加医生的笔记照片',
    },
    '3c4nk704': {
      'en': 'Parent or Guardian Signature',
      'de': 'Unterschrift',
      'es': 'Firma',
      'fr': 'Signature',
      'it': 'Firma',
      'ja': 'サイン',
      'zh_Hans': '签名',
    },
    's5wl9vvc': {
      'en': 'Sign your name below on the signature pad',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'bdsydx61': {
      'en': 'Submit Excuse',
      'de': 'Entschuldigung abgeben',
      'es': 'Enviar excusa',
      'fr': 'Soumettre une excuse',
      'it': 'Invia scusa',
      'ja': '言い訳を送信',
      'zh_Hans': '提交借口',
    },
    'g4ii48o3': {
      'en': 'Please enter full name of student',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'qyqungkz': {
      'en': 'Please enter full name of student',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'zc78o9dk': {
      'en': 'Please choose an option from the dropdown',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'wpmuhigb': {
      'en': 'Field is required',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    '5xxmxekw': {
      'en': 'Please choose an option from the dropdown',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    '36ys0doy': {
      'en': 'Field is required',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'qz3efcbz': {
      'en': 'Please choose an option from the dropdown',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    '3eezqw7e': {
      'en': 'A reason for student\'s absence must be provided',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    '8jcskcl8': {
      'en': 'Please choose an option from the dropdown',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'ig4pe40x': {
      'en': 'Report an Absence ',
      'de': 'Melden Sie eine Abwesenheit',
      'es': 'Reportar una ausencia',
      'fr': 'Signaler une absence',
      'it': 'Segnala un\'assenza',
      'ja': '欠席を報告する',
      'zh_Hans': '报告缺席',
    },
    'gj776w48': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // YourProfile
  {
    'f3lrbddq': {
      'en': 'Student',
      'de': 'Student',
      'es': 'Alumno',
      'fr': 'Étudiant',
      'it': 'Alunno',
      'ja': '学生',
      'zh_Hans': '学生',
    },
    'g5djk00i': {
      'en': 'Developer',
      'de': 'Entwickler',
      'es': 'Desarrollador',
      'fr': 'Développeur',
      'it': 'Sviluppatore',
      'ja': 'デベロッパー',
      'zh_Hans': '开发商',
    },
    'h2m279q1': {
      'en': 'Your Posts',
      'de': 'Deine Posts',
      'es': 'Tus publicaciones',
      'fr': 'Vos publications',
      'it': 'I tuoi post',
      'ja': 'あなたの投稿',
      'zh_Hans': '你的帖子',
    },
    '3eryex94': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // EditProfile
  {
    '2rhr4how': {
      'en': 'Display Name',
      'de': 'Anzeigename',
      'es': 'Nombre para mostrar',
      'fr': 'Afficher un nom',
      'it': 'Nome da visualizzare',
      'ja': '表示名',
      'zh_Hans': '显示名称',
    },
    'jb4h6tf6': {
      'en': 'Username',
      'de': 'Nutzername',
      'es': 'Nombre de usuario',
      'fr': 'Nom d\'utilisateur',
      'it': 'Nome utente',
      'ja': 'ユーザー名',
      'zh_Hans': '用户名',
    },
    'hpd4j8lo': {
      'en': '@',
      'de': '@',
      'es': '@',
      'fr': '@',
      'it': '@',
      'ja': '@',
      'zh_Hans': '@',
    },
    '4eqfcqb2': {
      'en': 'Save',
      'de': 'Speichern',
      'es': 'Ahorrar',
      'fr': 'sauvegarder',
      'it': 'Salva',
      'ja': '保存',
      'zh_Hans': '节省',
    },
    'r9459w4x': {
      'en': 'Edit Profile',
      'de': 'Profil bearbeiten',
      'es': 'Editar perfil',
      'fr': 'Editer le profil',
      'it': 'Modifica Profilo',
      'ja': 'プロファイル編集',
      'zh_Hans': '编辑个人资料',
    },
    'd78m0wlx': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // ReportABug
  {
    'tgvlttpa': {
      'en': 'Report a Bug',
      'de': 'Melde einen technischen Fehler',
      'es': 'Reportar un error',
      'fr': 'Signaler un bug',
      'it': 'Segnalare un bug',
      'ja': 'バグを報告',
      'zh_Hans': '报告错误',
    },
    'i0842x48': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // Settings
  {
    'iib8bwfn': {
      'en': 'Following',
      'de': 'Folgend',
      'es': 'Siguiendo',
      'fr': 'Suivant',
      'it': 'Seguente',
      'ja': '続く',
      'zh_Hans': '下列的',
    },
    'pfrajaiz': {
      'en': 'Followed Schools',
      'de': 'Gefolgte Schulen',
      'es': 'Escuelas seguidas',
      'fr': 'Ecoles suivies',
      'it': 'Scuole seguite',
      'ja': 'フォローした学校',
      'zh_Hans': '关注的学校',
    },
    'tokogtjz': {
      'en': 'Theme',
      'de': 'Thema',
      'es': 'Tema',
      'fr': 'Thème',
      'it': 'Tema',
      'ja': 'テーマ',
      'zh_Hans': '主题',
    },
    'xyrn7olz': {
      'en': 'Settings',
      'de': 'Einstellungen',
      'es': 'Ajustes',
      'fr': 'Réglages',
      'it': 'Impostazioni',
      'ja': '設定',
      'zh_Hans': '设置',
    },
    'vl0g7v2s': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // Following
  {
    'zn5h7pni': {
      'en': 'Profiles',
      'de': 'Profile',
      'es': 'Perfiles',
      'fr': 'Profils',
      'it': 'Profili',
      'ja': 'プロファイル',
      'zh_Hans': '简介',
    },
    'ldalnzak': {
      'en': '@imsocool',
      'de': '@ich bin so cool',
      'es': '@soy genial',
      'fr': '@je suis tellement cool',
      'it': '@imsocool',
      'ja': '@私はとてもクールです',
      'zh_Hans': '@我真酷',
    },
    '5hys2oib': {
      'en': '@omgwow',
      'de': '@omgwow',
      'es': '@omgwow',
      'fr': '@omgwow',
      'it': '@omgwow',
      'ja': '@omgwow',
      'zh_Hans': '@天哪',
    },
    'el9cr2cv': {
      'en': '@idk',
      'de': '@idk',
      'es': '@no sé',
      'fr': '@je ne sais pas',
      'it': '@idk',
      'ja': '@idk',
      'zh_Hans': '@idk',
    },
    'qronr77l': {
      'en': '@coolperson',
      'de': '@coole Person',
      'es': '@persona genial',
      'fr': '@Personne sympa',
      'it': '@coolperson',
      'ja': '@クールな人',
      'zh_Hans': '@酷的人',
    },
    'tsf7osq8': {
      'en': 'Tags',
      'de': 'Stichworte',
      'es': 'Etiquetas',
      'fr': 'Mots clés',
      'it': 'Tag',
      'ja': 'タグ',
      'zh_Hans': '标签',
    },
    'mrrftrni': {
      'en': '#groupssocool',
      'de': '#groupssocool',
      'es': '#grupossocool',
      'fr': '#groupssocool',
      'it': '#gruppicosìcool',
      'ja': '#groupssocool',
      'zh_Hans': '#groupssocool',
    },
    '15u9x8w4': {
      'en': '#omgwow',
      'de': '#omgwow',
      'es': '#omgwow',
      'fr': '#omgwow',
      'it': '#oddio',
      'ja': '#omgwow',
      'zh_Hans': '#天哪',
    },
    'kct1z0sz': {
      'en': '#idk',
      'de': '#idk',
      'es': '#no sé',
      'fr': '#je ne sais pas',
      'it': '#non so',
      'ja': '#idk',
      'zh_Hans': '#idk',
    },
    'psh7zy7l': {
      'en': '#coolgroup',
      'de': '#cooleGruppe',
      'es': '#grupocool',
      'fr': '#groupecool',
      'it': '#coolgruppo',
      'ja': '#クールグループ',
      'zh_Hans': '#coolgroup',
    },
    '1kmx6ks8': {
      'en': 'Following',
      'de': 'Folgend',
      'es': 'Siguiendo',
      'fr': 'Suivant',
      'it': 'Seguente',
      'ja': '続く',
      'zh_Hans': '下列的',
    },
    'ffea97fo': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // SchoolsFollowed
  {
    'm9qxt4fu': {
      'en': 'Easton Area High School',
      'de': 'Easton Area Highschool',
      'es': 'Escuela secundaria del área de Easton',
      'fr': 'École secondaire de la région d\'Easton',
      'it': 'Liceo della zona di Easton',
      'ja': 'イーストンエリア高校',
      'zh_Hans': '伊斯顿地区高中',
    },
    'vlqitd1o': {
      'en': 'Easton Area Middle School',
      'de': 'Easton Area Mittelschule',
      'es': 'Escuela secundaria del área de Easton',
      'fr': 'École intermédiaire de la région d\'Easton',
      'it': 'Scuola media dell\'area di Easton',
      'ja': 'イーストンエリア中学校',
      'zh_Hans': '伊斯顿地区中学',
    },
    'wc8rlbyt': {
      'en': 'Palmer Elementary School',
      'de': 'Palmer Grundschule',
      'es': 'Escuela Primaria Palmer',
      'fr': 'École primaire Palmer',
      'it': 'Scuola Elementare Palmari',
      'ja': 'パーマー小学校',
      'zh_Hans': '帕默小学',
    },
    '04c1x7v4': {
      'en': 'Forks Elementary School',
      'de': 'Forks Grundschule',
      'es': 'Escuela Primaria Forks',
      'fr': 'École primaire de la fourche',
      'it': 'Scuola elementare di Forks',
      'ja': 'フォークス小学校',
      'zh_Hans': '福克斯小学',
    },
    '0bn319g5': {
      'en': 'Tracy Elementary School',
      'de': 'Tracy Grundschule',
      'es': 'Escuela Primaria Tracy',
      'fr': 'École primaire Tracy',
      'it': 'Tracy Scuola Elementare',
      'ja': 'トレーシー小学校',
      'zh_Hans': '特雷西小学',
    },
    'hdkpi7im': {
      'en': 'Cheston Elementary School',
      'de': 'Cheston Grundschule',
      'es': 'Escuela Primaria Cheston',
      'fr': 'École primaire de Cheston',
      'it': 'Scuola elementare di Cheston',
      'ja': 'チェストン小学校',
      'zh_Hans': '切斯顿小学',
    },
    'jf9llyjv': {
      'en': 'Paxinosa Elementary School',
      'de': 'Paxinosa-Grundschule',
      'es': 'Escuela Primaria Paxinosa',
      'fr': 'École primaire Paxinosa',
      'it': 'Scuola elementare di Paxinosa',
      'ja': 'パキシノサ小学校',
      'zh_Hans': '帕西诺萨小学',
    },
    'aggkinoa': {
      'en': 'Shawnee Elementary School',
      'de': 'Shawnee-Grundschule',
      'es': 'Escuela Primaria Shawnee',
      'fr': 'École primaire Shawnee',
      'it': 'Shawnee Elementary School',
      'ja': 'ショーニー小学校',
      'zh_Hans': '肖尼小学',
    },
    '5s7gnv81': {
      'en': 'March Elementary School',
      'de': 'März Grundschule',
      'es': 'Escuela primaria de marzo',
      'fr': 'École primaire de mars',
      'it': 'Scuola elementare di marzo',
      'ja': 'マーチ小学校',
      'zh_Hans': '三月小学',
    },
    'dcfvvtq2': {
      'en': 'Easton Cyber Academy',
      'de': 'Easton Cyber-Akademie',
      'es': 'Academia cibernética de Easton',
      'fr': 'CyberAcadémie d\'Easton',
      'it': 'Easton Cyber Academy',
      'ja': 'イーストン サイバー アカデミー',
      'zh_Hans': '伊斯顿网络学院',
    },
    'fuyx7927': {
      'en': 'Schools',
      'de': 'Schulen',
      'es': 'Escuelas',
      'fr': 'Écoles',
      'it': 'Scuole',
      'ja': '学校',
      'zh_Hans': '学校',
    },
    'frd1d9ln': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // About
  {
    'dgv0p1hb': {
      'en': 'RoverLink',
      'de': 'RoverLink',
      'es': 'RoverLink',
      'fr': 'RoverLink',
      'it': 'RoverLink',
      'ja': 'ローバーリンク',
      'zh_Hans': '罗孚林克',
    },
    '489rrs9d': {
      'en': 'By Alexander Harrison, Andrew Xia, and Matthew You',
      'de': 'Von Alexander Harrison, Andrew Xia und Matthew You',
      'es': 'Por Alexander Harrison, Andrew Xia y Matthew You',
      'fr': 'Par Alexander Harrison, Andrew Xia et Matthew You',
      'it': 'Di Alexander Harrison, Andrew Xia e Matthew You',
      'ja': 'アレクサンダー・ハリソン、アンドリュー・シア、マシュー・ユー',
      'zh_Hans': '作者：Alexander Harrison、Andrew Xia 和 Matthew You',
    },
    'd0tkfia3': {
      'en': 'About the App',
      'de': 'Über die App',
      'es': 'Acerca de la aplicación',
      'fr': 'À propos de l\'application',
      'it': 'Informazioni sull\'app',
      'ja': 'アプリについて',
      'zh_Hans': '关于应用程序',
    },
    'mag9q2g4': {
      'en':
          'RoverLink is a mobile application for Android and iOS devices designed to help keep parents and the community up-to-date about EASD events and activities. Students can share photos and parents can notify the school of student absences.',
      'de':
          'RoverLink ist eine mobile Anwendung für Android- und iOS-Geräte, die entwickelt wurde, um Eltern und die Community über EASD-Veranstaltungen und -Aktivitäten auf dem Laufenden zu halten. Schüler können Fotos teilen und Eltern können die Schule über die Abwesenheit von Schülern informieren.',
      'es':
          'RoverLink es una aplicación móvil para dispositivos Android e iOS diseñada para ayudar a mantener a los padres y la comunidad actualizados sobre los eventos y actividades de EASD. Los estudiantes pueden compartir fotos y los padres pueden notificar a la escuela sobre las ausencias de los estudiantes.',
      'fr':
          'RoverLink est une application mobile pour les appareils Android et iOS conçue pour aider les parents et la communauté à rester informés des événements et des activités de l\'EASD. Les élèves peuvent partager des photos et les parents peuvent informer l\'école des absences des élèves.',
      'it':
          'RoverLink è un\'applicazione mobile per dispositivi Android e iOS progettata per mantenere i genitori e la comunità aggiornati sugli eventi e le attività dell\'EASD. Gli studenti possono condividere foto e i genitori possono notificare alla scuola le assenze degli studenti.',
      'ja':
          'RoverLink は、保護者やコミュニティが EASD のイベントや活動に関する最新情報を入手できるように設計された、Android および iOS デバイス用のモバイル アプリケーションです。生徒は写真を共有でき、保護者は生徒の欠席を学校に通知できます。',
      'zh_Hans':
          'RoverLink 是一款适用于 Android 和 iOS 设备的移动应用程序，旨在帮助家长和社区了解 EASD 事件和活动的最新信息。学生可以分享照片，家长可以通知学校学生缺勤。',
    },
    'ke56xjjx': {
      'en': '© 2022 Easton Area School District',
      'de': '© 2022 Schulbezirk Easton Area',
      'es': '© 2022 Distrito Escolar del Área de Easton',
      'fr': '© 2022 District scolaire de la région d\'Easton',
      'it': '© 2022 Distretto scolastico della zona di Easton',
      'ja': '© 2022 イーストン エリア学区',
      'zh_Hans': '© 2022 伊斯顿地区学区',
    },
    '12k6y5w4': {
      'en': 'Copyright and Licensing',
      'de': 'Urheberrecht und Lizenzierung',
      'es': 'Derechos de autor y licencias',
      'fr': 'Droits d\'auteur et licences',
      'it': 'Diritto d\'autore e licenza',
      'ja': '著作権とライセンス',
      'zh_Hans': '版权和许可',
    },
    'vsmag9zy': {
      'en': 'Terms of Use',
      'de': 'Nutzungsbedingungen',
      'es': 'Términos de Uso',
      'fr': 'Conditions d\'utilisation',
      'it': 'Termini di utilizzo',
      'ja': '利用規約',
      'zh_Hans': '使用条款',
    },
    'm53kjfoe': {
      'en': 'Privacy Policy',
      'de': 'Datenschutz-Bestimmungen',
      'es': 'Política de privacidad',
      'fr': 'Politique de confidentialité',
      'it': 'politica sulla riservatezza',
      'ja': 'プライバシーポリシー',
      'zh_Hans': '隐私政策',
    },
    '0igoc7rh': {
      'en': 'About',
      'de': 'Um',
      'es': 'Sobre',
      'fr': 'À propos de',
      'it': 'Di',
      'ja': '約',
      'zh_Hans': '关于',
    },
    '2npc64dd': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // SigningOut
  {
    'k3xhf8py': {
      'en': 'Logging Out...',
      'de': 'Ausloggen...',
      'es': 'Saliendo de tu cuenta...',
      'fr': 'Déconnecter...',
      'it': 'Disconnessione...',
      'ja': 'ログアウト...',
      'zh_Hans': '注销...',
    },
    '4nwadicu': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // TermsOfUse
  {
    'ciag688w': {
      'en': 'Terms Of Use',
      'de': 'Nutzungsbedingungen',
      'es': 'Términos de Uso',
      'fr': 'Conditions d\'utilisation',
      'it': 'Termini di utilizzo',
      'ja': '利用規約',
      'zh_Hans': '使用条款',
    },
    '8jsw7lwr': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // Login
  {
    'fw22h2r7': {
      'en': 'Sign In',
      'de': 'Einloggen',
      'es': 'Registrarse',
      'fr': 'S\'identifier',
      'it': 'Registrazione',
      'ja': 'ログイン',
      'zh_Hans': '登入',
    },
    '5uknzhia': {
      'en': 'Email Address',
      'de': 'E-Mail-Addresse',
      'es': 'Dirección de correo electrónico',
      'fr': 'Adresse e-mail',
      'it': 'Indirizzo e-mail',
      'ja': '電子メールアドレス',
      'zh_Hans': '电子邮件地址',
    },
    't3a5dj0t': {
      'en': 'Password',
      'de': 'Passwort',
      'es': 'Clave',
      'fr': 'Mot de passe',
      'it': 'Parola d\'ordine',
      'ja': 'パスワード',
      'zh_Hans': '密码',
    },
    'hy0koxex': {
      'en': 'Login',
      'de': 'Anmeldung',
      'es': 'Acceso',
      'fr': 'Connexion',
      'it': 'Login',
      'ja': 'ログイン',
      'zh_Hans': '登录',
    },
    'ldepbzep': {
      'en': 'Login as Guest',
      'de': 'Melden Sie sich als Gast an',
      'es': 'Iniciar sesión como invitado',
      'fr': 'Connectez-vous en tant qu\'invité',
      'it': 'Accedi come ospite',
      'ja': 'ゲストとしてログイン',
      'zh_Hans': '以访客身份登录',
    },
    'd59ena4o': {
      'en': 'Forgot Password?',
      'de': 'Passwort vergessen?',
      'es': '¿Has olvidado tu contraseña?',
      'fr': 'Mot de passe oublié?',
      'it': 'Ha dimenticato la password?',
      'ja': 'パスワードをお忘れですか？',
      'zh_Hans': '忘记密码？',
    },
    '0vvoynsh': {
      'en': 'Or use a social account to login',
      'de': 'Oder verwenden Sie ein soziales Konto, um sich anzumelden',
      'es': 'O use una cuenta social para iniciar sesión',
      'fr': 'Ou utilisez un compte social pour vous connecter',
      'it': 'Oppure usa un account social per accedere',
      'ja': 'または、ソーシャルアカウントを使用してログインします',
      'zh_Hans': '或使用社交账号登录',
    },
    '432nyxa1': {
      'en': 'Sign Up',
      'de': 'Anmeldung',
      'es': 'Inscribirse',
      'fr': 'S\'inscrire',
      'it': 'Iscrizione',
      'ja': 'サインアップ',
      'zh_Hans': '报名',
    },
    '46p8zoxf': {
      'en': 'Email Address',
      'de': 'E-Mail-Addresse',
      'es': 'Dirección de correo electrónico',
      'fr': 'Adresse e-mail',
      'it': 'Indirizzo e-mail',
      'ja': '電子メールアドレス',
      'zh_Hans': '电子邮件地址',
    },
    'uvpchzqb': {
      'en': 'Password',
      'de': 'Passwort',
      'es': 'Clave',
      'fr': 'Mot de passe',
      'it': 'Parola d\'ordine',
      'ja': 'パスワード',
      'zh_Hans': '密码',
    },
    'cuwd3isk': {
      'en': 'Confirm Password',
      'de': 'Passwort bestätigen',
      'es': 'Confirmar contraseña',
      'fr': 'Confirmez le mot de passe',
      'it': 'Conferma password',
      'ja': 'パスワードを認証する',
      'zh_Hans': '确认密码',
    },
    'vlydnlyl': {
      'en': 'Create Account',
      'de': 'Konto anlegen',
      'es': 'Crear una cuenta',
      'fr': 'Créer un compte',
      'it': 'Creare un profilo',
      'ja': 'アカウントを作成する',
      'zh_Hans': '创建账户',
    },
    'e0v4b1we': {
      'en': 'Or use a social account to create account',
      'de': 'Oder verwenden Sie ein soziales Konto, um ein Konto zu erstellen',
      'es': 'O use una cuenta social para crear una cuenta',
      'fr': 'Ou utilisez un compte social pour créer un compte',
      'it': 'Oppure usa un account social per creare un account',
      'ja': 'または、ソーシャル アカウントを使用してアカウントを作成します',
      'zh_Hans': '或者使用社交账号创建账号',
    },
    'zquwm76t': {
      'en': 'By clicking \"Create Account\" you agree to our ',
      'de': 'Indem Sie auf „Konto erstellen“ klicken, stimmen Sie unseren zu',
      'es': 'Al hacer clic en \"Crear cuenta\", aceptas nuestros',
      'fr': 'En cliquant sur \"Créer un compte\", vous acceptez nos',
      'it': 'Facendo clic su \"Crea account\" accetti i nostri',
      'ja': '「アカウントの作成」をクリックすることにより、あなたは私たちに同意したことになります',
      'zh_Hans': '单击“创建帐户”即表示您同意我们的',
    },
    '7q7e9rd3': {
      'en': 'Terms of Use',
      'de': 'Nutzungsbedingungen',
      'es': 'Términos de Uso',
      'fr': 'Conditions d\'utilisation',
      'it': 'Termini di utilizzo',
      'ja': '利用規約',
      'zh_Hans': '使用条款',
    },
    '7r5t8rbc': {
      'en': 'and',
      'de': 'und',
      'es': 'y',
      'fr': 'et',
      'it': 'e',
      'ja': 'と',
      'zh_Hans': '和',
    },
    '2s8cej1h': {
      'en': 'Privacy Policy',
      'de': 'Datenschutz-Bestimmungen',
      'es': 'Política de privacidad',
      'fr': 'Politique de confidentialité',
      'it': 'politica sulla riservatezza',
      'ja': 'プライバシーポリシー',
      'zh_Hans': '隐私政策',
    },
    '1htdiqyk': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // PrivacyPolicy
  {
    'yjmnhfal': {
      'en': 'Privacy Policy',
      'de': 'Datenschutz-Bestimmungen',
      'es': 'Política de privacidad',
      'fr': 'Politique de confidentialité',
      'it': 'politica sulla riservatezza',
      'ja': 'プライバシーポリシー',
      'zh_Hans': '隐私政策',
    },
    'd9hd9ruv': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // Onboarding
  {
    'nwm3x2ci': {
      'en': 'Connect With Peers',
      'de': 'Verbinde dich mit Gleichgesinnten',
      'es': 'Conectar con compañeros',
      'fr': 'Connectez-vous avec vos pairs',
      'it': 'Connettiti con i colleghi',
      'ja': '仲間とつながる',
      'zh_Hans': '与同行联系',
    },
    'mbvv5wuj': {
      'en':
          'Our platform creates a safe, friendly environment for students to form a shared sense of community.',
      'de':
          'Unsere Plattform schafft eine sichere, freundliche Umgebung für Studenten, um ein gemeinsames Gemeinschaftsgefühl zu bilden.',
      'es':
          'Nuestra plataforma crea un ambiente seguro y amigable para que los estudiantes formen un sentido compartido de comunidad.',
      'fr':
          'Notre plate-forme crée un environnement sûr et convivial pour les étudiants afin de former un sentiment partagé de communauté.',
      'it':
          'La nostra piattaforma crea un ambiente sicuro e amichevole in cui gli studenti possono formare un senso condiviso di comunità.',
      'ja': '私たちのプラットフォームは、学生がコミュニティの共有感覚を形成するための安全でフレンドリーな環境を作り出します。',
      'zh_Hans': '我们的平台为学生创造了一个安全、友好的环境，以形成共同的社区意识。',
    },
    '0vkk9jb4': {
      'en': 'Stay Up to Date',
      'de': 'Auf dem Laufenden bleiben',
      'es': 'Estar al día',
      'fr': 'Tiens-toi à jour',
      'it': 'Rimani aggiornato',
      'ja': '最新に保つ',
      'zh_Hans': '保持最新',
    },
    'lgulcrc0': {
      'en':
          'Keep up with the latest announcements and events from our district.',
      'de':
          'Bleiben Sie über die neuesten Ankündigungen und Veranstaltungen aus unserem Bezirk auf dem Laufenden.',
      'es':
          'Manténgase al día con los últimos anuncios y eventos de nuestro distrito.',
      'fr':
          'Tenez-vous au courant des dernières annonces et événements de notre district.',
      'it':
          'Tenere il passo con gli ultimi annunci ed eventi dal nostro distretto.',
      'ja': '私たちの地区からの最新の発表やイベントに遅れずについていきます。',
      'zh_Hans': '了解我们学区的最新公告和活动。',
    },
    'if1zlxpq': {
      'en': 'Report Absences',
      'de': 'Abwesenheit melden',
      'es': 'Reportar Ausencias',
      'fr': 'Signaler les absences',
      'it': 'Segnala le assenze',
      'ja': '欠勤の報告',
      'zh_Hans': '报告缺席',
    },
    'tn2qltve': {
      'en':
          'Roverlink makes it easy for you to submit absences to your local school office.',
      'de':
          'Roverlink macht es Ihnen leicht, Abwesenheiten bei Ihrem örtlichen Schulamt einzureichen.',
      'es':
          'Roverlink le facilita el envío de ausencias a la oficina de su escuela local.',
      'fr':
          'Roverlink vous permet de soumettre facilement les absences au bureau de votre école locale.',
      'it':
          'Roverlink semplifica la presentazione delle assenze all\'ufficio scolastico locale.',
      'ja': 'Roverlink を使用すると、欠席届を地元の学校事務所に簡単に提出できます。',
      'zh_Hans': 'Roverlink 使您可以轻松地向当地学校办公室提交缺勤。',
    },
    '9y5crtlg': {
      'en': 'Continue',
      'de': 'Fortsetzen',
      'es': 'Continuar',
      'fr': 'Continuer',
      'it': 'Continua',
      'ja': '継続する',
      'zh_Hans': '继续',
    },
  },
  // ForgotPassword
  {
    'r9qondpm': {
      'en':
          'We will send you an email with a link to reset your password, please enter the email associated with your account below.',
      'de':
          'Wir senden Ihnen eine E-Mail mit einem Link zum Zurücksetzen Ihres Passworts. Bitte geben Sie unten die mit Ihrem Konto verknüpfte E-Mail-Adresse ein.',
      'es':
          'Le enviaremos un correo electrónico con un enlace para restablecer su contraseña, ingrese el correo electrónico asociado con su cuenta a continuación.',
      'fr':
          'Nous vous enverrons un e-mail avec un lien pour réinitialiser votre mot de passe, veuillez entrer l\'e-mail associé à votre compte ci-dessous.',
      'it':
          'Ti invieremo un\'e-mail con un link per reimpostare la password, inserisci l\'e-mail associata al tuo account di seguito.',
      'ja':
          'パスワードをリセットするためのリンクが記載されたメールが送信されます。アカウントに関連付けられているメールアドレスを以下に入力してください。',
      'zh_Hans': '我们将向您发送一封电子邮件，其中包含重置密码的链接，请在下方输入与您的帐户关联的电子邮件。',
    },
    'c86nuu8p': {
      'en': 'Email Address',
      'de': 'E-Mail-Addresse',
      'es': 'Dirección de correo electrónico',
      'fr': 'Adresse e-mail',
      'it': 'Indirizzo e-mail',
      'ja': '電子メールアドレス',
      'zh_Hans': '电子邮件地址',
    },
    'wt8fom27': {
      'en': 'Send Link',
      'de': 'Link senden',
      'es': 'Enviar enlace',
      'fr': 'Envoyer un lien',
      'it': 'Invia il link',
      'ja': 'リンクを送る',
      'zh_Hans': '发送链接',
    },
    'ngmn4z29': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // Copyrights
  {
    'dl3iivct': {
      'en': 'Copyright and Licensing',
      'de': 'Urheberrecht und Lizenzierung',
      'es': 'Derechos de autor y licencias',
      'fr': 'Droits d\'auteur et licences',
      'it': 'Diritto d\'autore e licenza',
      'ja': '著作権とライセンス',
      'zh_Hans': '版权和许可',
    },
    'pdd9sz49': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // Theme
  {
    'kfmlfzcw': {
      'en': 'Theme',
      'de': 'Thema',
      'es': 'Tema',
      'fr': 'Thème',
      'it': 'Tema',
      'ja': 'テーマ',
      'zh_Hans': '主题',
    },
    'x8j2rbnw': {
      'en': 'Automatic',
      'de': 'Automatisch',
      'es': 'Automático',
      'fr': 'Automatique',
      'it': 'Automatico',
      'ja': '自動',
      'zh_Hans': '自动的',
    },
    '5pqvtm93': {
      'en': 'Dark',
      'de': 'Dunkel',
      'es': 'Oscuro',
      'fr': 'Sombre',
      'it': 'Scuro',
      'ja': '暗い',
      'zh_Hans': '黑暗的',
    },
    'pd2i1yqy': {
      'en': 'Light',
      'de': 'Licht',
      'es': 'Luz',
      'fr': 'Lumière',
      'it': 'Luce',
      'ja': '光',
      'zh_Hans': '光',
    },
    '7gagxf3w': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // FormSubmitted
  {
    'sltw2h07': {
      'en': 'Thank You!',
      'de': 'Danke!',
      'es': '¡Gracias!',
      'fr': 'Merci!',
      'it': 'Grazie!',
      'ja': 'ありがとう！',
      'zh_Hans': '谢谢你！',
    },
    'bxeung14': {
      'en':
          'Your child\'s absence has been recorded and sent to the appropriate grade-level office. Please contact your  child\'s school if you have any additional concerns.',
      'de':
          'Die Abwesenheit Ihres Kindes wurde erfasst und an das zuständige Klassenbüro weitergeleitet. Bitte kontaktieren Sie die Schule Ihres Kindes, wenn Sie weitere Bedenken haben.',
      'es':
          'La ausencia de su hijo ha sido registrada y enviada a la oficina del nivel de grado correspondiente. Comuníquese con la escuela de su hijo si tiene alguna inquietud adicional.',
      'fr':
          'L\'absence de votre enfant a été enregistrée et envoyée au bureau du niveau scolaire approprié. Veuillez contacter l\'école de votre enfant si vous avez d\'autres préoccupations.',
      'it':
          'L\'assenza di tuo figlio è stata registrata e inviata all\'ufficio di livello scolastico appropriato. Contatta la scuola di tuo figlio se hai ulteriori dubbi.',
      'ja': 'お子様の欠席は記録され、適切な学年レベルのオフィスに送信されました。さらに懸念がある場合は、お子様の学校にお問い合わせください。',
      'zh_Hans': '您孩子的缺勤已被记录并发送到相应的年级办公室。如果您有任何其他疑虑，请联系您孩子的学校。',
    },
    'eyutm0ou': {
      'en': 'Continue',
      'de': 'Fortsetzen',
      'es': 'Continuar',
      'fr': 'Continuer',
      'it': 'Continua',
      'ja': '継続する',
      'zh_Hans': '继续',
    },
    'kp0pbrdb': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // AddContentSelector
  {
    'f25z3d1z': {
      'en': 'Share',
      'de': 'Teilen',
      'es': 'Cuota',
      'fr': 'Partager',
      'it': 'Condividere',
      'ja': 'シェア',
      'zh_Hans': '分享',
    },
    'xcdyw8hv': {
      'en': 'Turn in Absence Excuse',
      'de': 'Entschuldigung für Abwesenheit abgeben',
      'es': 'Entregar excusa de ausencia',
      'fr': 'Rendre une excuse d\'absence',
      'it': 'Consegna in Assenza Scusa',
      'ja': '欠勤の言い訳を提出する',
      'zh_Hans': '上交缺席借口',
    },
    't7nb2xmc': {
      'en': 'Add Post',
      'de': 'Beitrag hinzufügen',
      'es': 'Añadir publicación',
      'fr': 'Ajouter un article',
      'it': 'Aggiungi messaggio',
      'ja': '投稿を追加',
      'zh_Hans': '添加帖子',
    },
  },
  // SocialPost
  {
    'jqn6iwma': {
      'en': '•',
      'de': '•',
      'es': '•',
      'fr': '•',
      'it': '•',
      'ja': '•',
      'zh_Hans': '•',
    },
    'iklzch53': {
      'en': '4',
      'de': '4',
      'es': '4',
      'fr': '4',
      'it': '4',
      'ja': '4',
      'zh_Hans': '4个',
    },
    '8xg00nve': {
      'en': '4',
      'de': '4',
      'es': '4',
      'fr': '4',
      'it': '4',
      'ja': '4',
      'zh_Hans': '4个',
    },
  },
  // CustomAppBar
  {
    'z9j9w26h': {
      'en': '6',
      'de': '6',
      'es': '6',
      'fr': '6',
      'it': '6',
      'ja': '6',
      'zh_Hans': '6个',
    },
    'y0g4iir5': {
      'en': '6',
      'de': '6',
      'es': '6',
      'fr': '6',
      'it': '6',
      'ja': '6',
      'zh_Hans': '6个',
    },
  },
  // CustomAppBarCopy
  {
    'm6x8ui7t': {
      'en': '6',
      'de': '6',
      'es': '6',
      'fr': '6',
      'it': '6',
      'ja': '6',
      'zh_Hans': '6个',
    },
    'i9hhqjo1': {
      'en': '6',
      'de': '6',
      'es': '6',
      'fr': '6',
      'it': '6',
      'ja': '6',
      'zh_Hans': '6个',
    },
  },
  // Announcement
  {
    '9uhbwmcj': {
      'en': 'Title',
      'de': 'Titel',
      'es': 'Título',
      'fr': 'Titre',
      'it': 'Titolo',
      'ja': '題名',
      'zh_Hans': '标题',
    },
  },
  // Miscellaneous
  {
    '3572m3oi': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    '2orputwt': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    '87s2j00w': {
      'en':
          'In order to add calendar events this app requires permission to access the calendar.',
      'de':
          'Um Kalenderereignisse hinzuzufügen, benötigt diese App die Berechtigung zum Zugriff auf den Kalender.',
      'es':
          'Para agregar eventos de calendario, esta aplicación requiere permiso para acceder al calendario.',
      'fr':
          'Afin d\'ajouter des événements de calendrier, cette application nécessite l\'autorisation d\'accéder au calendrier.',
      'it':
          'Per aggiungere eventi del calendario questa app richiede l\'autorizzazione per accedere al calendario.',
      'ja': 'カレンダー イベントを追加するには、このアプリにカレンダーへのアクセス許可が必要です。',
      'zh_Hans': '为了添加日历事件，此应用程序需要访问日历的权限。',
    },
    '27uisxge': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    '7cd0q1oi': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'tnoj489c': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'af1r9e4f': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'ord8iu06': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'ledzzqxl': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    '9lc86xlj': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    '55bzymjq': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'xzjcgl5m': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'k5cd3sc5': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'hl4mynpz': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'dda570ya': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    '0w6cdejq': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    '94y8vwx2': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'lhsh4feb': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    '3h9uz7mu': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'yfl28dcy': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    '880yr452': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    'zpq5nh8r': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
    '1kguvq3s': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'it': '',
      'ja': '',
      'zh_Hans': '',
    },
  },
].reduce((a, b) => a..addAll(b));
